--- #YAML:1.0
name:               Dancer-Plugin-Preprocess-Sass
version:            0.01
abstract:           Generate CSS files from Sass/SCSS files
author:
    - Michal Wojciechowski <odyniec@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:      1.307
    Test::More:  0
    Text::Sass:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
